language: node_js
node_js:
  - 0.10

env:
  - DEBUG=hotpotato:* NO_PERF=1
  - PERF=1

before_script: ulimit -Sn 5000; ulimit -Hn 5000

deploy:
  provider: npm
  email: me@samcday.com.au
  api_key:
    secure: N1pXQfcwpMcOexiCDBRXYfQ3WbJP+9RNZZbayb1iNFuhEm50/HxJLdUcV8UInxKkUuS5lSIsWX1KbPKEEtbo6IR5wLTpVUzfYblVmYQI6yoI1XjhcBdYVdlS1uKZUD5ACEfV3Ut112G70XcWks3Drf7/zAuAdvlR3A1mT4E96jQ=
  on:
    tags: true
    all_branches: true
    node_js: 0.10
